src/Entity/User.php
<?php

/**
 * Created by devinthehood.
 * Project: symfony-skeleton
 * User: Jul6art
 * Date: 21/11/2019
 * Time: 21:39.
 */

namespace App\Entity;

use App\Entity\Constants\UserRole;
use Doctrine\Common\Collections\ArrayCollection;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\BlameableEntityAwareTrait;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\EntityListeners({"App\EntityListener\UserEntityListener"})
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields="email", repositoryMethod="findByUniqueEmail")
 * @UniqueEntity(fields="username", repositoryMethod="findByUniqueUsername")
 *
 * @method string|null getLocale()
 * @method             setLocale(string $locale)
 * @method string|null getTheme()
 * @method             setTheme(string $theme)
 */
class User extends BaseUser
{
    use TimestampableEntity;
    use BlameableEntityAwareTrait;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=1, nullable=true)
     *
     * @Assert\NotBlank()
     * @Assert\Length(min=1,max=1)
     */
    protected $gender;

    /**
     * @var string|null
     *
     * @ORM\Column(name="firstname", type="string", length=50, nullable=true)
     * @Assert\Length(max="50")
     */
    protected $firstname;

    /**
     * @var string|null
     *
     * @ORM\Column(name="lastname", type="string", length=80, nullable=true)
     * @Assert\Length(max="80")
     */
    protected $lastname;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Group")
     * @Assert\Count(min="1", max="1")
     * @ORM\JoinTable(name="user_group",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;

    /**
     * @var ArrayCollection|UserSetting[]
     * @ORM\OneToMany(targetEntity="App\Entity\UserSetting", mappedBy="user", cascade={"all"})
     */
    protected $settings;

    /**
     * User constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->settings = new ArrayCollection();
    }

    /**
     * @return string|null
     */
    public function getGender(): ?string
    {
        return $this->gender;
    }

    /**
     * @param string|null $gender
     *
     * @return User
     */
    public function setGender(?string $gender): User
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    /**
     * @param string|null $firstname
     *
     * @return User
     */
    public function setFirstname(?string $firstname): User
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    /**
     * @param string|null $lastname
     *
     * @return User
     */
    public function setLastname(?string $lastname): User
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFullname(): ?string
    {
        return ucwords(sprintf('%s %s', $this->firstname, $this->lastname));
    }

    /**
     * @return ArrayCollection|UserSetting[]
     */
    public function getSettings()
    {
        return $this->settings;
    }

    /**
     * @param UserSetting $setting
     *
     * @return User
     */
    public function addSetting(UserSetting $setting): self
    {
        if (!$this->settings->contains($setting)) {
            $this->settings[] = $setting;
            $setting->setUser($this);
        }

        return $this;
    }

    /**
     * @param UserSetting $setting
     *
     * @return User
     */
    public function removeSetting(UserSetting $setting): self
    {
        if ($this->settings->contains($setting)) {
            $this->settings->removeElement($setting);
            if ($setting->getUser() === $this) {
                $setting->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @param string $name
     *
     * @return UserSetting|null
     */
    public function getSetting(string $name): ?UserSetting
    {
        foreach ($this->settings as $setting) {
            if ($setting->getName() === $name) {
                return $setting;
            }
        }

        return null;
    }

    /**
     * @param string $name
     * @param string $value
     *
     * @return self
     */
    public function setSetting(string $name, string $value): self
    {
        $setting = $this->getSetting($name);

        if (null === $setting) {
            $setting = (new UserSetting())
                ->setName($name);

            $this->addSetting($setting);
        }

        $setting->setValue($value);

        return $this;
    }

    /**
     * @param string $name
     *
     * @return bool
     */
    public function hasSetting(string $name): ?bool
    {
        return null !== $this->getSetting($name);
    }

    /**
     * @param $name
     * @param $arguments
     *
     * @return string|null
     */
    public function __call($name, $arguments)
    {
        $property = $this->camelToSnake(substr($name, 3));

        if (0 === strpos($name, 'get')) {
            return $this->$property;
        } elseif (0 === strpos($name, 'set')) {
            $this->$property = $arguments[0];

            return $this;
        }
    }

    private function camelToSnake($input)
    {
        return strtolower(preg_replace('/(?<!^)[A-Z]/', '_$0', $input));
    }

    /**
     * @param $name
     *
     * @return string|null
     */
    public function __get($name)
    {
        if ($this->hasSetting($name)) {
            return $this->getSetting($name)->getValue();
        }

        return null;
    }

    /**
     * @param string $name
     * @param string $value
     *
     * @return User
     */
    public function __set($name, $value)
    {
        return $this->setSetting($name, $value);
    }

    /**
     * @return bool
     */
    public function isAdmin(): bool
    {
        return $this->hasRole(UserRole::ROLE_ADMIN) or $this->hasRole(UserRole::ROLE_SUPER_ADMIN);
    }
}

templates/bundles/FOSUserBundle/Profile/edit.html.twig
{% extends 'layout/layout_form.html.twig' %}

{% set breadcrumb = false %}

{% block page_title %}
    {{ 'title.account.edit'|trans({}, 'title') }}
{% endblock page_title %}

{% block page_actions %}
    <div class="pull-right btn-group">
        <a class="btn bg-blue-grey white waves-effect" href="{{ path('fos_user_profile_show') }}">
            <i class="material-icons">arrow_left</i> <span class="hidden-xs">{{ 'button.back'|trans({}, 'button') }}</span>
        </a>
    </div>
{% endblock page_actions %}

{% block form_title %}
    <span{{ translate_in_place('form.account.profile.title', {}, 'form') }}>
        {{ 'form.account.profile.title'|trans({}, 'form')}}
    </span>
{% endblock form_title %}

{% block form_content %}
{% include '@FOSUser/Profile/edit_content.html.twig' %}
{% endblock form_content %}

{% block form_footer %}
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-4 col-md-6 col-md-offset-6">
            <div class="btn-group btn-group-justified">
                <a class="btn btn-block waves-effect bg-blue-grey" href="{{ referer|default(path('fos_user_profile_show')) }}">
                    <i class="material-icons">cancel</i> <span class="hidden-xs">{{ 'button.cancel'|trans({}, 'button') }}</span>
                </a>
                <div class="btn-group">
                    <button class="btn btn-block waves-effect bg-{{ theme_name() }}" type="submit"
                            {{ is_granted(constant('App\\Security\\Voter\\FunctionalityVoter::WATCH_FORM'), 'App\\Entity\\Functionality') ? 'disabled' }}>
                        <i class="material-icons">save</i> <span class="hidden-xs">{{ 'button.save'|trans({}, 'button') }}</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock form_footer %}

templates/bundles/FOSUserBundle/Profile/edit_content.html.twig
<div class="row">
    <div class="col-sm-6">
        {{ form_row(form.gender) }}
    </div>
    <div class="col-sm-6">
        {{ form_row(form.username) }}
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        {{ form_row(form.firstname) }}
    </div>
    <div class="col-sm-6">
        {{ form_row(form.lastname) }}
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        {{ form_row(form.email) }}
    </div>
</div>

templates/bundles/FOSUserBundle/Profile/show.html.twig
{% extends 'layout/layout_details.html.twig' %}

{% set breadcrumb = false %}

{% block page_title %}
    {{ 'title.account.profile'|trans({}, 'title') }}
{% endblock page_title %}

{% block page_actions %}
    {% if is_granted(constant('App\\Security\\Voter\\UserVoter::LIST'), 'App\\Entity\\User') %}
        <div class="pull-right btn-group">
            <a class="btn bg-blue-grey white waves-effect" href="{{ path('admin_user_list') }}">
                <i class="material-icons">arrow_left</i> <span class="hidden-xs">{{ 'button.back'|trans({}, 'button') }}</span>
            </a>
        </div>
    {% endif %}
{% endblock page_actions %}

{% block details_title %}
    <span{{ translate_in_place('details.profile.title', {}, 'details') }}>
        {{ 'details.profile.title'|trans({}, 'details')|raw }}
    </span>
{% endblock details_title %}

{% block details_sidebar_left %}
    <div class="card profile-card">
        <div class="profile-header bg-{{ theme_name() }}">&nbsp;</div>
        <div class="profile-body">
            <div class="image-area">
                <img src="{{ asset('build/images/user-lg.jpg') }}" alt="AdminBSB - Profile Image">
            </div>
            <div class="content-area">
                <h3>{{ user.fullname }}</h3>
                <p>{{ user.username }}</p>
                <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
            </div>
        </div>
        {% if is_granted(constant('App\\Security\\Voter\\UserVoter::CHANGE_AVATAR'), user) %}
            <div class="profile-footer">
                <button class="btn bg-blue-grey btn-lg waves-effect btn-block">{{ 'details.profile.links.avatar.mine'|trans({}, 'details') }}</button>
            </div>
        {% endif %}
    </div>
{% endblock details_sidebar_left %}

{% block details_content %}
    {% include '@FOSUser/Profile/show_content.html.twig' %}
{% endblock details_content %}

{% block details_footer %}
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-sm-offset-8 col-md-3 col-md-offset-9">
            <div class="btn-group btn-group-justified">
                <a class="btn btn-block waves-effect bg-{{ theme_name() }}" href="{{ path('fos_user_profile_edit') }}">
                    <i class="material-icons">edit</i> <span class="hidden-xs">{{ 'button.edit'|trans({}, 'button') }}</span>
                </a>
            </div>
        </div>
    </div>
{% endblock details_footer %}

{% block details_after %}
    {% if is_granted(constant('App\\Security\\Voter\\UserVoter::AUDIT'), user) %}
        <div class="row clearfix">
            <div class="col-xs-12">
                {{ render(controller('App\\Controller\\DefaultController::audit', {
                    class: 'App\\Entity\\User',
                    id: user.id,
                })) }}
            </div>
        </div>
    {% endif %}

    {% if is_granted(constant('App\\Security\\Voter\\UserVoter::SELF_DELETE'), user) %}
        {% include 'user/_self_delete.html.twig' %}
    {% endif %}
{% endblock details_after %}

templates/bundles/FOSUserBundle/Profile/show_content.html.twig
<div class="table-responsive">
    <table class="table table table-bordered table-striped table-hover">
        <tbody>
            <tr>
                <th>
                    <span{{ translate_in_place('table.head.user.id', {}, 'table') }}>
                        {{ 'table.head.user.id'|trans({}, 'table') }}
                    </span>
                </th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>
                    <span{{ translate_in_place('table.head.user.gender', {}, 'table') }}>
                        {{ 'table.head.user.gender'|trans({}, 'table') }}
                    </span>
                </th>
                <td><span class="label bg-blue-grey">{{ ('table.user.gender.' ~ user.gender)|trans({}, 'table') }}</span></td>
            </tr>
            <tr>
                <th>
                    <span{{ translate_in_place('table.head.user.name', {}, 'table') }}>
                        {{ 'table.head.user.name'|trans({}, 'table') }}
                    </span>
                </th>
                <td>{{ user.fullname }}</td>
            </tr>
            <tr>
                <th>
                    <span{{ translate_in_place('table.head.user.username', {}, 'table') }}>
                        {{ 'table.head.user.username'|trans({}, 'table') }}
                    </span>
                </th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>
                    <span{{ translate_in_place('table.head.user.email', {}, 'table') }}>
                        {{ 'table.head.user.email'|trans({}, 'table') }}
                    </span>
                </th>
                <td><a class="white-space-nowrap" href="mailto:{{ user.email }}">{{ user.email }}</a></td>
            </tr>
        </tbody>
    </table>
</div>